name: 'Ambient Action'
description: 'Create sessions on the Ambient Code Platform from any GitHub workflow'
author: 'Ambient Code'

branding:
  icon: 'play-circle'
  color: 'purple'

inputs:
  api-url:
    description: 'Ambient Code Platform backend API URL'
    required: true
  api-token:
    description: 'Bot user bearer token for the Ambient API'
    required: true
  project:
    description: 'Ambient project/namespace name'
    required: true
  prompt:
    description: 'Initial prompt for the session'
    required: true
  display-name:
    description: 'Human-readable session display name'
    required: false
    default: ''
  repos:
    description: 'JSON array of repos, e.g. [{"url": "...", "branch": "main", "autoPush": true}]'
    required: false
    default: ''
  labels:
    description: 'JSON object of labels for the session'
    required: false
    default: ''
  environment-variables:
    description: 'JSON object of environment variables to inject into the runner'
    required: false
    default: ''
  timeout:
    description: 'Session timeout in minutes'
    required: false
    default: '30'
  model:
    description: 'Model override (e.g. claude-sonnet-4-20250514)'
    required: false
    default: ''
  workflow:
    description: 'JSON workflow object, e.g. {"gitUrl": "https://...", "branch": "main", "path": "workflows/my-wf"}'
    required: false
    default: ''
  wait:
    description: 'Wait for session completion before exiting'
    required: false
    default: 'false'
  poll-interval:
    description: 'Seconds between status polls when waiting'
    required: false
    default: '15'
  no-verify-ssl:
    description: 'Disable SSL certificate verification (for self-signed certs)'
    required: false
    default: 'false'

outputs:
  session-name:
    description: 'Created session name'
    value: ${{ steps.run.outputs.session-name }}
  session-uid:
    description: 'Created session UID'
    value: ${{ steps.run.outputs.session-uid }}
  session-phase:
    description: 'Final session phase (only set when wait is true)'
    value: ${{ steps.run.outputs.session-phase }}
  session-result:
    description: 'Session result text (only set when wait is true)'
    value: ${{ steps.run.outputs.session-result }}

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: pip install --quiet requests>=2.31.0

    - name: Create session
      id: run
      shell: bash
      env:
        INPUT_API_URL: ${{ inputs.api-url }}
        INPUT_API_TOKEN: ${{ inputs.api-token }}
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_PROMPT: ${{ inputs.prompt }}
        INPUT_DISPLAY_NAME: ${{ inputs.display-name }}
        INPUT_REPOS: ${{ inputs.repos }}
        INPUT_LABELS: ${{ inputs.labels }}
        INPUT_ENV_VARS: ${{ inputs.environment-variables }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_WORKFLOW: ${{ inputs.workflow }}
        INPUT_WAIT: ${{ inputs.wait }}
        INPUT_POLL_INTERVAL: ${{ inputs.poll-interval }}
        INPUT_NO_VERIFY_SSL: ${{ inputs.no-verify-ssl }}
      run: |
        OUTPUT_FILE="${RUNNER_TEMP}/ambient-session-output.json"

        # Write prompt to a temp file to avoid shell interpretation of
        # backticks, $, parentheses, quotes, etc. in multi-line prompts.
        PROMPT_FILE="${RUNNER_TEMP}/ambient-prompt.txt"
        printf '%s' "$INPUT_PROMPT" > "$PROMPT_FILE"

        ARGS=(
          --api-url "$INPUT_API_URL"
          --api-token "$INPUT_API_TOKEN"
          --project "$INPUT_PROJECT"
          --prompt-file "$PROMPT_FILE"
          --timeout "${INPUT_TIMEOUT:-30}"
          --poll-interval "${INPUT_POLL_INTERVAL:-15}"
          --output-file "$OUTPUT_FILE"
        )

        if [ -n "$INPUT_DISPLAY_NAME" ]; then
          ARGS+=(--display-name "$INPUT_DISPLAY_NAME")
        fi
        if [ -n "$INPUT_REPOS" ]; then
          ARGS+=(--repos "$INPUT_REPOS")
        fi
        if [ -n "$INPUT_LABELS" ]; then
          ARGS+=(--labels "$INPUT_LABELS")
        fi
        if [ -n "$INPUT_ENV_VARS" ]; then
          ARGS+=(--env-vars "$INPUT_ENV_VARS")
        fi
        if [ -n "$INPUT_MODEL" ]; then
          ARGS+=(--model "$INPUT_MODEL")
        fi
        if [ -n "$INPUT_WORKFLOW" ]; then
          ARGS+=(--workflow "$INPUT_WORKFLOW")
        fi
        if [ "$INPUT_WAIT" = "true" ]; then
          ARGS+=(--wait)
        fi
        if [ "$INPUT_NO_VERIFY_SSL" = "true" ]; then
          ARGS+=(--no-verify-ssl)
        fi

        python3 "${GITHUB_ACTION_PATH}/create_session.py" "${ARGS[@]}"

        if [ -f "$OUTPUT_FILE" ]; then
          SESSION_NAME=$(python3 -c "import json; d=json.load(open('$OUTPUT_FILE')); print(d.get('session_name', ''))")
          SESSION_UID=$(python3 -c "import json; d=json.load(open('$OUTPUT_FILE')); print(d.get('session_uid', ''))")
          SESSION_PHASE=$(python3 -c "import json; d=json.load(open('$OUTPUT_FILE')); print(d.get('session_phase', ''))")
          SESSION_RESULT=$(python3 -c "import json; d=json.load(open('$OUTPUT_FILE')); print(d.get('session_result', ''))")

          echo "session-name=$SESSION_NAME" >> "$GITHUB_OUTPUT"
          echo "session-uid=$SESSION_UID" >> "$GITHUB_OUTPUT"
          echo "session-phase=$SESSION_PHASE" >> "$GITHUB_OUTPUT"
          {
            echo "session-result<<GHEOF"
            echo "$SESSION_RESULT"
            echo "GHEOF"
          } >> "$GITHUB_OUTPUT"
        else
          echo "session-name=" >> "$GITHUB_OUTPUT"
          echo "session-uid=" >> "$GITHUB_OUTPUT"
          echo "session-phase=CreateFailed" >> "$GITHUB_OUTPUT"
          echo "session-result=" >> "$GITHUB_OUTPUT"
        fi
