name: 'Ambient Action'
description: 'Create sessions on the Ambient Code Platform from any GitHub workflow'
author: 'Ambient Code'

branding:
  icon: 'play-circle'
  color: 'purple'

inputs:
  api-url:
    description: 'Ambient Code Platform backend API URL'
    required: true
  api-token:
    description: 'Bot user bearer token for the Ambient API'
    required: true
  project:
    description: 'Ambient project/namespace name'
    required: true
  prompt:
    description: 'Initial prompt for the session'
    required: true
  display-name:
    description: 'Human-readable session display name'
    required: false
    default: ''
  repos:
    description: 'JSON array of repos, e.g. [{"url": "...", "branch": "main", "autoPush": true}]'
    required: false
    default: ''
  labels:
    description: 'JSON object of labels for the session'
    required: false
    default: ''
  environment-variables:
    description: 'JSON object of environment variables to inject into the runner'
    required: false
    default: ''
  timeout:
    description: 'Session timeout in minutes'
    required: false
    default: '30'
  model:
    description: 'Model override (e.g. claude-sonnet-4-20250514)'
    required: false
    default: ''
  wait:
    description: 'Wait for session completion before exiting'
    required: false
    default: 'false'
  poll-interval:
    description: 'Seconds between status polls when waiting'
    required: false
    default: '15'
  no-verify-ssl:
    description: 'Disable SSL certificate verification (for self-signed certs)'
    required: false
    default: 'false'

outputs:
  session-name:
    description: 'Created session name'
  session-uid:
    description: 'Created session UID'
  session-phase:
    description: 'Final session phase (only set when wait is true)'
  session-result:
    description: 'Session result text (only set when wait is true)'

runs:
  using: 'docker'
  image: 'Dockerfile'
